# Generated by Django 5.1.5 on 2025-02-05 03:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_requestlogs_alter_currentbalance_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogs',
            name='request_method',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
